#!/usr/bin/env bash
# pxe-genmenu.sh — regenerate the dynamic ISO-listing menus.
#
# Scans three directories on the NAS:
#   /mnt/tank/system/pxe/http/extras/utils/*.iso    -> utils.ipxe
#   /mnt/tank/system/pxe/http/extras/distros/*.iso  -> distros.ipxe
#   /mnt/tank/system/pxe/http/extras/live/*.iso     -> live.ipxe
#
# Each .iso becomes a menu item whose name is the filename (minus
# the `.iso` extension). The menu picks it up automatically — no
# edits needed when an ISO is added or removed, just re-run this
# script.
#
# Invocation:
#   /mnt/tank/system/apps-config/pxe/pxe-genmenu.sh
#
# Runs automatically after pxe-download.sh (same cronjob) and can
# be re-run anytime. Writes its output files with uid/gid 1000 so
# dnsmasq (in the pxe container) can serve them over TFTP.

set -euo pipefail

HTTP_BASE="${HTTP_BASE:-http://10.10.5.10:8080}"
EXTRAS_DIR="${EXTRAS_DIR:-/mnt/tank/system/pxe/http/extras}"
TFTP_DIR="${TFTP_DIR:-/mnt/tank/system/pxe/tftp}"

# Bonus non-ISO items that ship alongside the ISO listings — these
# go at the TOP of the corresponding menu since they're small and
# fast-loading. Syntax: label::target::boot-type::path  (boot-type
# is "chain" | "kernel" — sanboot is auto-chosen for everything in
# the listings).

UTILS_EXTRAS=(
    "Memtest86+ v8.00 (TFTP, tiny)::memtest::kernel::tftp://10.10.5.10/memtest.bin"
    "UEFI Shell v2.2 (TianoCore)::uefishell::chain::${HTTP_BASE}/extras/uefishell/Shell.efi"
    "ZFSBootMenu v3.1.0 recovery::zbm::chain::${HTTP_BASE}/extras/zbm/zfsbootmenu-recovery.EFI"
)

# Distros that aren't ISO-based (netboot kernel+initrd). Listed up
# top in the Distros menu.
DISTRO_EXTRAS=(
    "Debian 13 trixie netinst::debian-13::debian-netinst::${HTTP_BASE}/extras/debian-13"
    "Debian 12 bookworm netinst::debian-12::debian-netinst::${HTTP_BASE}/extras/debian-12"
    "Alpine Linux 3.21 (netboot)::alpine::alpine-netboot::${HTTP_BASE}/extras/alpine"
)

# Live CDs: no kernel+initrd extras, pure ISO listing.
LIVE_EXTRAS=()

# Derive a human-readable label from a filename. Replace hyphens +
# underscores with spaces; pass through otherwise. Caller can prefix
# anything it wants.
label_for() {
    local name="$1"
    # Strip .iso, then replace - _ with space
    name="${name%.iso}"
    echo "$name" | tr '_-' '  '
}

# Generate a single menu file.
# Args: MENU_NAME DEST_PATH DIR EXTRAS_VAR
gen_menu() {
    local title="$1" dest="$2" dir="$3" extras_var="$4"

    # Indirect expansion of the extras array by name (bash-ism).
    local -n extras="$extras_var"

    {
        cat <<'HEADER'
#!ipxe
# Auto-generated by pxe-genmenu.sh. Do NOT edit manually.
# Regenerates on every pxe-download.sh run, or via:
#   /mnt/tank/system/apps-config/pxe/pxe-genmenu.sh

HEADER

        echo ":start"
        echo "menu ${title}"

        # Hard-coded extras first (not ISO-discovered).
        if (( ${#extras[@]} > 0 )); then
            echo "item --gap -- --- Built-in ---"
            for e in "${extras[@]}"; do
                local lbl tgt
                IFS='::' read -r lbl _ tgt _ <<< "${e//::/$'\t'}"
                # Robust split
                lbl="${e%%::*}"; rest="${e#*::}"
                tgt="${rest%%::*}"
                echo "item ${tgt}  ${lbl}"
            done
        fi

        # Dynamic: *.iso in the extras dir.
        local isos=()
        if [[ -d "$dir" ]]; then
            while IFS= read -r -d '' f; do
                isos+=("$f")
            done < <(find "$dir" -maxdepth 1 -type f -name '*.iso' -print0 | sort -z)
        fi

        if (( ${#isos[@]} > 0 )); then
            echo "item --gap -- --- ISOs ---"
            for iso in "${isos[@]}"; do
                local base; base=$(basename "$iso")
                local tgt; tgt="${base%.iso}"
                local size_mb; size_mb=$(du -m "$iso" 2>/dev/null | awk '{print $1}')
                local lbl; lbl=$(label_for "$base")
                echo "item ${tgt}  ${lbl} (${size_mb} MB ISO)"
            done
        elif (( ${#extras[@]} == 0 )); then
            echo "item --gap -- (nothing available — run pxe-download.sh)"
        fi

        cat <<'NAV'
item --gap -- ---
item back  Back to main menu
choose --default back --timeout 60000 target || goto back
goto ${target}

NAV

        # Extras targets
        for e in "${extras[@]}"; do
            local lbl tgt kind path
            lbl="${e%%::*}"; rest="${e#*::}"
            tgt="${rest%%::*}"; rest="${rest#*::}"
            kind="${rest%%::*}"; path="${rest#*::}"
            echo ":${tgt}"
            echo "echo Booting ${lbl}"
            case "$kind" in
                chain)
                    echo "chain --autofree ${path} || goto fail"
                    echo "goto start"
                    ;;
                kernel)
                    echo "imgfree"
                    echo "kernel ${path}"
                    echo "boot || goto fail"
                    ;;
                debian-netinst)
                    echo "imgfree"
                    echo "kernel ${path}/linux auto=true priority=critical"
                    echo "initrd ${path}/initrd.gz"
                    echo "boot || goto fail"
                    ;;
                alpine-netboot)
                    echo "imgfree"
                    echo "kernel ${path}/vmlinuz-lts initrd=initramfs-lts modloop=${path}/modloop-lts ip=dhcp alpine_repo=http://dl-cdn.alpinelinux.org/alpine/v3.21/main"
                    echo "initrd ${path}/initramfs-lts"
                    echo "boot || goto fail"
                    ;;
            esac
            echo ""
        done

        # ISO targets — sanboot each
        for iso in "${isos[@]}"; do
            local base tgt
            base=$(basename "$iso"); tgt="${base%.iso}"
            echo ":${tgt}"
            echo "echo Booting ${base} (sanboot — loads whole ISO into RAM; large ones take a minute)"
            echo "sanboot --no-describe ${HTTP_BASE}${iso#/mnt/tank/system/pxe/http} || goto fail"
            echo "goto start"
            echo ""
        done

        cat <<'FOOTER'
:fail
echo
echo Boot failed. Check file size on NAS:
echo   curl -sI ${HTTP_BASE}/extras/...
echo
prompt Press any key to return...
goto start

:back
exit
FOOTER
    } > "$dest.tmp"

    mv -f "$dest.tmp" "$dest"
    chown 1000:1000 "$dest"
    echo "wrote $dest ($(wc -l < "$dest") lines)"
}

gen_menu "Utilities"       "$TFTP_DIR/utils.ipxe"   "$EXTRAS_DIR/utils"   UTILS_EXTRAS
gen_menu "Distributions"   "$TFTP_DIR/linux.ipxe"   "$EXTRAS_DIR/distros" DISTRO_EXTRAS
gen_menu "Live CDs"        "$TFTP_DIR/live.ipxe"    "$EXTRAS_DIR/live"    LIVE_EXTRAS

echo "pxe-genmenu complete"
